### ISSUE TITLE
Item icon is removed when processed

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/WoodAndStone#13]
Noticed this while using the Quern interface - while processing the last item from the input slot, on the first click the icon is removed and you see only the progress bar. 
If the last item to process is the only item overall, you completely loose the information of _what_ is processed.

Possible solutions:
- either keep the item icon in the input slot as long as it is processed
- show some kind of indicator what is processed (possible way to do this is to show a transparent version of the result if the output slot is empty)

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
