### ISSUE TITLE
Journal entry about clay/hearth/bricks

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/WoodAndStone#14]
I'm not sure if I've missed it, but a journal entry about clay would be nice at the time the player _picks up clay_ for the first time. 
I think you get used to the journal entries that it might take a while until you noticed the additional recipe for hand crafting.

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
