### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/WoodAndStone#15]
I think this one is quite important for a full gameplay experience - sound effects.

I'll just list what I have in mind so far:
- [ ] sounds for workstations (hacking, cooking, burning fire, hammering, ...)
- [ ] better sounds for mining, chopping trees, ...
- [ ] scribble sound on new journal entry
- [ ] ...

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
