### ISSUE TITLE
Quern build stages

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/WoodAndStone#16]
Turning the Quern into a single block replaced the fun part of building a multiblock structure by using a recipe. 

A possible alternative would be some kind of construction process of a single block. In terms of the quern, the following block shapes are needed:
- [ ] single quern stone
- [ ] single quern stone with stick attached in the middle
- [ ] two quern stones placed on top of each other with stick in the middle
  _Using a stick_ on the last shape could turn the block into the final Quern. The attached image illustrates this process:
  ![blockconstruction](https://f.cloud.github.com/assets/1448874/2301865/d6147946-a160-11e3-8c08-6d676299512f.png)

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
