### ISSUE TITLE
New Journal Chapter Icons

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/WoodAndStone#17]
- [ ] Create new icons for journal chapters.
- [ ] Refactor icon usage into a new texture sheet with atlas

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
