### ISSUE TITLE
Add missing UI backgrounds and unify naming

### ISSUE THREAD

**Issue by skaldarnar** [Terasology/WoodAndStone#18]
- [ ] add missing CraftInHand background
- [ ] unifiy file names, e.g. to "<craftingType>BG.png"

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
