### ISSUE TITLE
Quirks in world gen after faceted overhaul

### ISSUE THREAD

**Issue by Cervator** [Terasology/WoodAndStone#27]
At least I figure these aren't quite right :-)

It looks like the vertical-ness is off. The trees (only one type?) go up till they're cut by a vertical chunk boundary and the lakes go down similarly (there's a pile of water then a flat bottom way below)

![terasology-141007220350-1152x700](https://cloud.githubusercontent.com/assets/1063833/4554351/9bf960f6-4eac-11e4-94fa-0bb087cb8184.jpg)

![terasology-141007221041-1152x700](https://cloud.githubusercontent.com/assets/1063833/4554354/b1bf55d0-4eac-11e4-9f63-ea2439f0f753.jpg)

![terasology-141007221058-1152x700](https://cloud.githubusercontent.com/assets/1063833/4554355/b3c6cac0-4eac-11e4-9b8b-b4ba1a87de27.jpg)

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
