### ISSUE TITLE
Better clarification that "blocks" don't typically drop

### ISSUE THREAD

**Issue by ghost** [Terasology/WoodAndStone#31]
_Cervator edit: I suggest we add a journal entry event the first time the player breaks a dirt or stone block, and no actual block drops. Something funny like "Huh, that was weird. I thought something bigger would drop when I broke that block. Maybe I need better tools first. I guess it is a different world after all!"_

I consider it very strange that I'm not able to do anything with, for example. sand, when I have this module enabled. Is this a bug or a feature?

**Comment by skaldarnar** [comment]
Its a feature in WaS that block drops are not the standard way you expect. Since the gameplay focuses  on survival and evolving technologies, the standard grass or sand blocks don't drop anymore. 

Probably it does make sense to have shovels that allow you to get soils as blocks for basic terraforming, etc.

Just to make sure: trees and leaves should drop items when they are destroyed...

**Comment by getsmp** [comment]
Is there an option to turn this off? It's really weird for newcomers from Minecraft world like me.

**Comment by Cervator** [comment]
You do not want to have WoodAndStone the module enabled for anything but the Throughout The Ages gameplay :-) Everything else should drop blocks naturally, but TTA is meant to make it harder to build shelter and such. Unsupported blocks even collapse (or are supposed to) to make it even harder (like trying to dig a shelter)

Maybe we should make a humorous entry in the journal when the player first digs a block and no block drops: "Wait .. breaking this block was weird. I thought something bigger would drop. Maybe this is indeed a different world"

After all, actually having a cubic meter of soil drop in a perfect block you can somehow fit hundreds off in your pocket isn't actually very natural, hehe.

It won't be possible to turn this off in Throughout The Ages but you may later gain the ability through tools to get full blocks. An early example is after you get an axe so you can chop tree trunks, you can place those again normally like blocks (and build a shelter)

**Comment by getsmp** [comment]
But if I disable WaS, it is impossible to craft. How to deal with it?

**Comment by Cervator** [comment]
Well, you either have Throughout The Ages active and craft using its system, or have something else active instead. The crafting system in TTA is unique to that gameplay, it isn't the game's global crafting system :-)

For instance if you enable JoshariasSurvival instead, with TTA not enabled, you get the crafting system in JS

There probably will be a general crafting system at some point - we used to have one in the legacy version of the game, but it doesn't currently work.

This is the drawback of still being in pre-alpha - most the time you need to use the game console to get to some of the interesting content. For instance with WildAnimals enabled you still don't get any deer spawning unless you do so yourself via "spawnPrefab deer" in the console

**Comment by getsmp** [comment]
Trying to craft something with JS, press G and nothing happens. How to craft? :)

**Comment by Cervator** [comment]
In JS you actually start with a workbench of sorts in your hot bar. You place that in the world, point at it, press 'e' (which "activates" various things) and you get a few slots to put ingredients in as well as a large set of recipes to the right :-)

It helps to follow the journal in both TTA and JS - press 'j' and scroll up :-)

I'm going to rename this issue as a suggestion we add a journal entry the first time the player breaks a dirt of stone block and gets no "block drop"

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
