### ISSUE TITLE
Planting CornSeed causes java.lang.RuntimeException: component null

### ISSUE THREAD

**Issue by Josharias** [Terasology/WoodAndStone#33]
https://gist.github.com/Josharias/1e537b2a6c2355960482

- Gen world
- Give cornfruit, stoneknife, and tilledearth
- Craft cornseed
- Place tilledearth and right click the cornfruit on to the tilledearth

**Comment by Cervator** [comment]
This also seems to happen on placing a tree sapling gotten from a leaf drop. Birch in my case.

**Comment by Cervator** [comment]
Both fixed! Huzzah :-)
