### ISSUE TITLE
Quirk in dueling overrides causing block drops from leaves, not item drops

### ISSUE THREAD

**Issue by Cervator** [Terasology/WoodAndStone#35]
@Josharias this one might be for you, or maybe @MarcinSc has an idea how to sort it out

After the recent module reorganization / extraction the leaf overrides in WoodAndStone are targeting PlantPack, but so are new overrides in AnotherWorldPlants. And the original prefab being overridden is now blank where it seems it could retain the PartOfTree piece - although I'm unsure.

In any case it would appear the override in AnotherWorldPlants is winning, which only sets the PartOfTree, not the BlockDropGrammar - the override in WoodAndStone does that. As a result no twigs are dropping, so progress in TTA is blocked pretty quick

Specific example:

* Previous origin: https://github.com/Terasology/PlantPack/blob/master/assets/prefabs/tree/birch/BirchLeaf.prefab - now empty, but still there
* Old override: https://github.com/Terasology/WoodAndStone/blob/master/overrides/PlantPack/prefabs/tree/birch/BirchLeaf.prefab - still there, unchanged, still points at PlantPack
* New override: https://github.com/Terasology/AnotherWorldPlants/blob/master/overrides/PlantPack/prefabs/tree/birch/BirchLeaf.prefab - takes precedence and doesn't contain BlockDropGrammar

I don't remember what the objective was, but I figure it was to keep things better organized. But it puzzles me that only part of the assets from PlantPack moved, leaving an empty shell behind.

Incidentally I tried redirecting the override in WoodAndStone to instead override AnotherWorldPlants, but it doesn't look like it worked.

If at all either of you find a few minutes tonight to look at this please do, as it is overwise a block for the release I'm trying to do tomorrow :-) If not I'll just try best effort to fix it for the release then we can re-break to refactor further.

In the tree, part of the tree - wonder if animated gifs work!

![inthetreepartofthetree](https://cloud.githubusercontent.com/assets/1063833/7443663/b02d475a-f12b-11e4-8d0b-fe53c2509e4c.gif)

**Comment by Josharias** [comment]
Hrm.  Both if those should likely be deltas as apposed to overrides.  I'll
fix tomorrow morning.  Thanks for finding this bug, Cervator.
The empty shell is there so that both can extend the entity and not have
competing overrides like we have now.

**Comment by Cervator** [comment]
Thanks :-)

I'll work on the launcher and write-ups in the meantime

**Comment by Cervator** [comment]
Closing as fixed! Thanks @Josharias :-)
