### ISSUE TITLE
Extract `org.terasology.herbalism` to separate module named "Herbalism"

### ISSUE THREAD

**Issue by DarkWeird** [Terasology/WoodAndStone#58]
This Package Duplicated in Alchemy module.
It need extraction.

See https://github.com/Terasology/Alchemy/issues/13

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
