### ISSUE TITLE
Extract `org.terasology.heat` in separate module

### ISSUE THREAD

**Issue by DarkWeird** [Terasology/WoodAndStone#60]
Duplication with module `WorkstationCrafting`

See https://github.com/Terasology/WorkstationCrafting/issues/14

**Comment by jdrueckert** [comment]
This module was removed from the omega line-up.
If at all, re-integrating it into omega is only planned long-term at which point it needs to be revisited in detail and overhauled.
Until then, this issue only adds noise to the currently relevant module-land issues and will therefore be closed.
